### ISSUE TITLE
Path_to_waveguide Manhatten Check Bug

### ISSUE THREAD

**Issue by StephenHLin** [SiEPIC/SiEPIC_EBeam_PDK#181]
Trying to convert a path with more than 1 perpendicular corner into a waveguide results in the 'path is not Manhattan (vertical,horizontal) error.

Also: would it be possible to have a boolean in the function parameters to suppress for auto-layout purposes? e.g. `path_to_waveguide(cell=cell,warning=FALSE)`

![image](https://user-images.githubusercontent.com/16215213/36020032-09394866-0d36-11e8-8873-36b15c53b766.png)

**Comment by lukasc-ubc** [comment]
@StephenHLin do you know if this is still an issue? 

thanks

**Comment by StephenHLin** [comment]
Resolved, the bug is no longer present when testing in SiEPIC 0.5.11
