### ISSUE TITLE
Bent CDC Pin Rec

### ISSUE THREAD

**Issue by amistry-ubc** [SiEPIC/SiEPIC_EBeam_PDK#183]
For certain bend-to-straight radii and bus waveguide combinations, the pin rec is not centered correctly.

![image](https://user-images.githubusercontent.com/32209315/36185276-1f6ea684-10ed-11e8-9a8e-aa5456f4b7d3.png)

Bus radius = 5um, width = 450nm

**Comment by mustafacc** [comment]
Seems like there is a misalignment between pinrec and waveguide tip:

![capture](https://user-images.githubusercontent.com/8067688/36185459-0f3d3c0c-10ee-11e8-99ae-386eff91d530.PNG)

**Comment by lukasc-ubc** [comment]
Is this only in the CDC component, or others too?

**Comment by mustafacc** [comment]
Bent_Coupled_Halfring as well, but the bent CDC is based off of that PCell.
