### ISSUE TITLE
Klayout 0.25 integration with Lumerical Interconnect

### ISSUE THREAD

**Issue by liaquat85** [SiEPIC/SiEPIC_EBeam_PDK#191]
Dear Lukas, 

I tried to connect the Klayout 0.25 with Lumerical Interconnect. I followed the procedure as given in 
https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/wiki/Installation-instructions

When I try to connect the KLayout with Lumerical Interconnect I am given this error 

![image](https://user-images.githubusercontent.com/6405871/43976592-c1685cb0-9ca6-11e8-98c8-80648f4d0150.png)

What should I do ?

**Comment by lukasc-ubc** [comment]
Hi @liaquat85,
Can you please let me know which versions of all the softwares you are using?  (make sure they are the latest ones).  The error you are seeing is in INTERCONNECT's python integration script (lumapi.py, line 87).  
I'll try in the next day or two to see if I get this error in the latest versions...

**Comment by lukasc-ubc** [comment]
Can you also please send me the GDS file that you are trying to simulate? I would like to see if I can reproduce your problem.

**Comment by liaquat85** [comment]
Hi  Lukas,

 

This is the file I want to simulate. 

 

Regards, 

Liaquat Ali

**Comment by liaquat85** [comment]
Hi Lukas ,

 

I am using Klayout 0.25.3

Lumerical Interconnect  7.0.1332

Regards, 

Liaquat Ali

**Comment by lukasc-ubc** [comment]
Can you please try INTERCONNECT 8?

**Comment by liaquat85** [comment]
Hi  Lukas,

 

Can you please tell how to referecen the Ebeam library PDK if one is using it in his research work ? 

 

Regards, 

Liaquat Ali

**Comment by lukasc-ubc** [comment]
Hi @liaquat85,

The version of the Lumerical tool you are using is quite old, so I suspect that the issue is that the Python integration is outdated.  Try the latest version.

For your question about referencing the tool, do you mean what to put in a publication?  There is a paper suggested for citing this work on the main page: https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK
You can also put the GitHub EBeam URL in the references section.

regards
Lukas

**Comment by gitelfin** [comment]
Does this application requires specific license ?? I got the following error:
![image](https://user-images.githubusercontent.com/37954861/44333356-d9aab000-a46e-11e8-88aa-6f8a50017f32.png)

**Comment by lukasc-ubc** [comment]
Yes there is a KLayout integration license feature


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
