### ISSUE TITLE
PIN issue with Cell DoubleBus_Ring  

### ISSUE THREAD

**Issue by oscar-ubc** [SiEPIC/SiEPIC_EBeam_PDK#193]
The PIN for the cell DoubleBus_Ring is not showing properly. Error message was "PIN_LENGTH" was not defined. The issue was that in the script  pin_length=PIN_LENGTH, but PIN_LENGTH was not defined. After changing the line to "from SiEPIC._globals import PIN_LENGTH as pin_length", the issue is solved.

**Comment by StephenHLin** [comment]
Good catch, I found this too.

I will commit it shortly, thanks Oscar!
