### ISSUE TITLE
Waveguide Issue in EBeam- Components & models [Technology EBeam]

### ISSUE THREAD

**Issue by oscar-ubc** [SiEPIC/SiEPIC_EBeam_PDK#194]
The Waveguide Pcell in the EBeam- Components & models [Technology EBeam] has a 'Width' parameter and a 'Widths' parameter.  When change 'Width', the waveguide width changes, and the value in'Widths' changes as well. When change values in 'Widths', nothing happened.

**Comment by lukasc-ubc** [comment]
This coerce thing isn't working.. disabling it for now.
