### ISSUE TITLE
Lumerical software not found.

### ISSUE THREAD

**Issue by muktillc** [SiEPIC/SiEPIC_EBeam_PDK#196]
I am getting an error saying that Lumerical software not found when I try to export the library to Lumerical. Am I missing something here? Please help.

**Comment by lukasc-ubc** [comment]
Can you provide more details?  Do you have any Lumerical software installed?  Which ones?  What path are the tools installed in?

**Comment by muktillc** [comment]
I have the Lumerical Suite installed. All the tools are installed in the folder "C:\Program Files\Lumerical"

**Comment by lukasc-ubc** [comment]
What is the error message?  What licenses do you have?  Do you have the KLayout integration license?


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
