### ISSUE TITLE
instantiate GDS library elements

### ISSUE THREAD

**Issue by joamatab** [SiEPIC/SiEPIC_EBeam_PDK#197]
instances do not show anymore on the library

![image](https://user-images.githubusercontent.com/4514346/46969079-cc263680-d069-11e8-92ac-ed8eb29bb07f.png)

how can we add back the instances into the library so we can instantiate them with letter I?

**Comment by joamatab** [comment]
it works with layout 0.24
![image](https://user-images.githubusercontent.com/4514346/46982674-0e636e00-d092-11e8-9498-bd75e50ebea3.png)

**Comment by lukasc-ubc** [comment]
what technology is active in the layout?  Look on the bottom left of the screen.  0.25 libraries are tied to a specific technologies, and don’t show up if the wrong one is chosen.
