### ISSUE TITLE
Klayout and Lumerical Integration 

### ISSUE THREAD

**Issue by liaquat85** [SiEPIC/SiEPIC_EBeam_PDK#199]
I have updated some of the modules in KLayout and the integration does not work of KLayout and Lumerical INTERCONNECT?
I am setting up the Lumerical INTERCONNECT with KLayout like this 
![image](https://user-images.githubusercontent.com/6405871/47592943-0e3d5b00-d93b-11e8-88d2-4cc43332d834.png)
It starts the Lumerical INTERCONNECT but on that software it gives this error.
![image](https://user-images.githubusercontent.com/6405871/47592961-21502b00-d93b-11e8-8cde-eb2346a508e5.png)
And then KLAYOUT give this error
![image](https://user-images.githubusercontent.com/6405871/47592972-3036dd80-d93b-11e8-8934-429719d29a2a.png)

Can you tell me what is the problem here

**Comment by lukasc-ubc** [comment]
The issue is as described in the GUI message: you do not have an interconnect license that includes the KLayout integration. 


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
