### ISSUE TITLE
different Layout of directional coupler on a Mac El Capitan

### ISSUE THREAD

**Issue by yaohuic** [SiEPIC/SiEPIC_EBeam_PDK#202]
1. I was testing Klayout with SIEPIC 0.3.52 on my old El Capitan Mac Pro. I found that the following default Ebeam Pcell "ebeam_dc_te1550" has a different shape as below. Lc=10um.  The "S-bend" on each port now looks two 90-degree "ARC"s, hence the whole Pcell structure takes a large area as 30.1um x 22.2um. I am not sure what is the root cause, or a particular software-compatible/python-compatible issue with an old Mac OSX. 

2. The layout on my windows laptop and (the fabricated layouts passed through edx layout check) shows 22.1um x6.2um dimensions with slimmed "S-bend". Such Pcell different between my Mac and windows machine may lead me to inconsistent layout works. In this case, all connected layout structures I made with beam_dc_te1550 on windows laptop will show "overlapped/disconnected pins" errors on my Mac. Such "false" errors are counter-productive in multiple users/machines scenario.

Hence, I am very interested to understand why it happens.  Any known workarounds ?

![screen shot 2019-02-28 at 22 25 53](https://user-images.githubusercontent.com/47613391/53687962-246d8480-3d3c-11e9-9c6c-4e1704a66a33.png)

**Comment by lukasc-ubc** [comment]
Can you send me the screenshot for the one that looks different?


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by yaohuic** [comment]
Follow is the screenshot on El Captian Mac:
default  ebeam_y_1550 vs. "Ebeam_dc_te1550"
![screen shot 2019-03-03 at 18 44 57](https://user-images.githubusercontent.com/47613391/53699063-98636780-3de4-11e9-81eb-384077e58a5f.png)

**Comment by yaohuic** [comment]
Following is screenshot on windows laptop: (The standard layout look)
default ebeam_y_1550 vs. Ebeam_dc_te1550, both have similar vertical distance between two ports. 
![image](https://user-images.githubusercontent.com/47613391/53699149-977f0580-3de5-11e9-9357-0b1e118bbc52.png)

**Comment by yaohuic** [comment]
And I have an minor question about layer colors and filling patterns through Klayout:

1.  Feels like Mac has better visual effects on the filling patterns of SiEPIC PDK;
2.  Klayout on Windows normally does not show the relevant filling patterns;
3.  Is it a Klayout (windows vs. Mac) issue?  or "color/graphic coding difference between windows and Mac?

**Comment by lukasc-ubc** [comment]
Please try turning off "Show Layers without Fill"
<img width="264" alt="image" src="https://github.com/SiEPIC/SiEPIC_EBeam_PDK/assets/15843200/1ecee612-2728-4c96-9bf1-20849cf03f2b">
