### ISSUE TITLE
Why my EBeam PDK libraries lost even if I install EBeam_PDK 0.3.32

### ISSUE THREAD

**Issue by zhangxlei** [SiEPIC/SiEPIC_EBeam_PDK#235]
@lukasc-ubc 
Dear Professor lukas,

I have installed klayout(0.26.11) and Siepic_EBeam_PDK(0.3.32) in Windows 10. I have used the software and your PDK well. 

But today after I update the Siepic_EBeam_PDK, the SiEPIC_EBeam_PDK libraries is lost. 
I have change the version of klayout from 0.26.7 to 0.26.11 and reinstalled the package the libraries still lost.
![image](https://user-images.githubusercontent.com/20834450/115681651-4ea0b700-a387-11eb-872e-d63b56e1c5c8.png)
![image](https://user-images.githubusercontent.com/20834450/115681753-65470e00-a387-11eb-9d56-0028ae3451b9.png)

In addition, the SiEPIC-Tools has no problem.
![image](https://user-images.githubusercontent.com/20834450/115682368-fb7b3400-a387-11eb-866b-930f478fc3f9.png)

Could you give me some suggestions?

Looking forward to hearing from you!
Best regards!
Weiling

**Comment by lukasc-ubc** [comment]
Could you please check the error log?  Under the File menu.  Perhaps there are errors when initializing the libraries.

**Comment by zhangxlei** [comment]
Thanks for your suggestion!
There is a warning or error in log viewer.
![image](https://user-images.githubusercontent.com/20834450/115823734-6c2e5900-a439-11eb-8726-6c2a21a570f3.png)
But how to solve the problem?

**Comment by zhangxlei** [comment]
In addition, I want to install klayout and the PDK on another computer, it had the same problem and error in log viewer.

**Comment by lukasc-ubc** [comment]
That’s an easy fix. 

In that file, add a line at the top:

from pya import Path

You’ll need an external editor since the file is read only in KLayout when in the salt folder. 


Lukas Chrostowski
Professor, Electrical and Computer Engineering
University of British Columbia
Quantum Matter Institute
Member, College of the Royal Society of Canada
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
https://qmi.ubc.ca/about/directory/lukas-chrostowski

**Comment by lukasc-ubc** [comment]
actually, we need Path, Point, etc.

So perhaps:

from pya import *

probably this needs to be fixed in other files too.

**Comment by lukasc-ubc** [comment]
I released v0.3.33. can you see if that fixes it? thanks.

**Comment by zhangxlei** [comment]
I have tried add a line at the top: from pya import Path/ from pya import *, it seems to make no difference.

**Comment by zhangxlei** [comment]
I have updated your new release, the problem still exists.

**Comment by zhangxlei** [comment]
it seems not to add a line at the top, I add the code into the second line. It is right?
![image](https://user-images.githubusercontent.com/20834450/115828247-06919b00-a440-11eb-8993-6b043789d015.png)

**Comment by zhangxlei** [comment]
After I add the code into second line, the log viewer has no error or warning but the library still lost.

**Comment by zhangxlei** [comment]
I have changed the version to 0.3.30, the libraries reappears and the problem is solved. I guess there is something the matter with your code of 0.3.32.

**Comment by ANT-Jocelyn** [comment]
@lukasc-ubc I'm having this same issue with the current version 0.3.34. The library import scripts are no longer running automatically successfully when KLayout is opened. They can be run manually from within KLayout each time the software is opened to show the libraries but you have to accept the following exception: 
![image](https://user-images.githubusercontent.com/67347748/121076372-92167f80-c793-11eb-9786-17e0e95be46d.png)

**Comment by mustafacc** [comment]
Hi @ANT-Jocelyn  , which version of KLayout are you currently using?

**Comment by ANT-Jocelyn** [comment]
@mustafacc 0.26.12

**Comment by lukasc-ubc** [comment]
Hi @ANT-Jocelyn 
sorry for the slow response.  Do you still have this problem, say in SiEPIC-Tools 0.3.79 and the SiEPIC-EBeam-PDK 0.3.36?  If it works with the EBeam PDK, compare your library loading code with the EBeam one.

**Comment by ANT-Jocelyn** [comment]
@lukasc-ubc @mustafacc this error seems to be fixed in the SiEPIC Tools 0.3.79 and EBeam-PDK 0.3.36 releases, thanks for checking.
